{"context":"ExceptionHandler","level":"error","message":"app.use() requires a middleware function","stack":["TypeError: app.use() requires a middleware function\n    at Function.use (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\platform-express\\node_modules\\express\\lib\\application.js:210:11)\n    at ExpressAdapter.use (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\adapters\\http-adapter.js:14:30)\n    at NestApplication.use (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\nest-application.js:144:26)\n    at C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\nest-factory.js:133:40\n    at Function.run (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\errors\\exceptions-zone.js:10:13)\n    at Proxy.<anonymous> (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\nest-factory.js:132:46)\n    at Proxy.<anonymous> (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\nest-factory.js:181:54)\n    at C:\\Users\\33641\\webservicetp1\\dist\\apps\\api-match\\webpack:\\webservicetp1\\apps\\api-match\\src\\main.ts:24:7\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\33641\\webservicetp1\\node_modules\\tslib\\tslib.js:114:62)"],"timestamp":"2022-03-31T10:19:16.147Z"}
{"level":"error","message":"Error: listen EADDRINUSE: address already in use :::3333","stack":["NestApplication"],"timestamp":"2022-03-31T10:46:15.120Z"}
{"level":"error","message":"ApiResourceStructureInvalidException: Sent resource structure is invalid\n    at ValidationPipe.resourceExceptionFactory [as exceptionFactory] (C:\\Users\\33641\\webservicetp1\\dist\\apps\\api-match\\webpack:\\webservicetp1\\libs\\api\\core\\abstract\\src\\lib\\api-abstract.controller.ts:54:7)\n    at ValidationPipe.transform (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\common\\pipes\\validation.pipe.js:65:30)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at resolveParamValue (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:147:23)\n    at async Promise.all (index 0)\n    at pipesFn (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:150:13)\n    at C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:37:30","stack":["ApiExceptionFilter"],"timestamp":"2022-04-14T07:37:29.617Z"}
{"level":"error","message":"ApiResourceStructureInvalidException: Sent resource structure is invalid\n    at ValidationPipe.resourceExceptionFactory [as exceptionFactory] (C:\\Users\\33641\\webservicetp1\\dist\\apps\\api-match\\webpack:\\webservicetp1\\libs\\api\\core\\abstract\\src\\lib\\api-abstract.controller.ts:54:7)\n    at ValidationPipe.transform (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\common\\pipes\\validation.pipe.js:65:30)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at resolveParamValue (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:147:23)\n    at async Promise.all (index 0)\n    at pipesFn (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:150:13)\n    at C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:37:30","stack":["ApiExceptionFilter"],"timestamp":"2022-04-14T07:37:31.354Z"}
{"level":"error","message":"ApiResourceStructureInvalidException: Sent resource structure is invalid\n    at ValidationPipe.resourceExceptionFactory [as exceptionFactory] (C:\\Users\\33641\\webservicetp1\\dist\\apps\\api-match\\webpack:\\webservicetp1\\libs\\api\\core\\abstract\\src\\lib\\api-abstract.controller.ts:51:10)\n    at ValidationPipe.transform (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\common\\pipes\\validation.pipe.js:65:30)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at resolveParamValue (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:147:23)\n    at async Promise.all (index 0)\n    at pipesFn (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:150:13)\n    at C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:37:30","stack":["ApiExceptionFilter"],"timestamp":"2022-04-14T07:38:38.223Z"}
{"level":"error","message":"ApiResourceStructureInvalidException: Sent resource structure is invalid\n    at ValidationPipe.resourceExceptionFactory [as exceptionFactory] (C:\\Users\\33641\\webservicetp1\\dist\\apps\\api-match\\webpack:\\webservicetp1\\libs\\api\\core\\abstract\\src\\lib\\api-abstract.controller.ts:51:10)\n    at ValidationPipe.transform (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\common\\pipes\\validation.pipe.js:65:30)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at resolveParamValue (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:147:23)\n    at async Promise.all (index 0)\n    at pipesFn (C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:150:13)\n    at C:\\Users\\33641\\webservicetp1\\node_modules\\@nestjs\\core\\router\\router-execution-context.js:37:30","stack":["ApiExceptionFilter"],"timestamp":"2022-04-14T07:38:39.478Z"}
{"level":"error","message":"NotFoundException: Not Found\n    at handleDocumentNotFound (C:\\Users\\33641\\webservicetp1\\dist\\apps\\api-match\\webpack:\\webservicetp1\\libs\\api\\repository\\error\\src\\lib\\api-repository-error.ts:10:11)\n    at C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\operators\\catchError.ts:117:35\n    at OperatorSubscriber._this._error (C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\operators\\OperatorSubscriber.ts:79:13)\n    at OperatorSubscriber.Subscriber.error (C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\Subscriber.ts:91:12)\n    at OperatorSubscriber.Subscriber._error (C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\Subscriber.ts:124:24)\n    at OperatorSubscriber.Subscriber.error (C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\Subscriber.ts:91:12)\n    at C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\observable\\innerFrom.ts:93:34","stack":["NotFoundExceptionFilter"],"timestamp":"2022-04-14T07:40:26.710Z"}
{"level":"error","message":"NotFoundException: Not Found\n    at handleDocumentNotFound (C:\\Users\\33641\\webservicetp1\\dist\\apps\\api-match\\webpack:\\webservicetp1\\libs\\api\\repository\\error\\src\\lib\\api-repository-error.ts:10:11)\n    at C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\operators\\catchError.ts:117:35\n    at OperatorSubscriber._this._error (C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\operators\\OperatorSubscriber.ts:79:13)\n    at OperatorSubscriber.Subscriber.error (C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\Subscriber.ts:91:12)\n    at OperatorSubscriber.Subscriber._error (C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\Subscriber.ts:124:24)\n    at OperatorSubscriber.Subscriber.error (C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\Subscriber.ts:91:12)\n    at C:\\Users\\33641\\webservicetp1\\node_modules\\rxjs\\src\\internal\\observable\\innerFrom.ts:93:34","stack":["NotFoundExceptionFilter"],"timestamp":"2022-04-14T07:40:27.991Z"}
{"level":"error","message":"Error: listen EADDRINUSE: address already in use :::3333","stack":["NestApplication"],"timestamp":"2022-04-14T07:48:04.963Z"}
